---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      name: java
      labels:
        app: web
        version: blue
    spec:
      containers:
      - name: app
        image: zubairbhat722/my-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 500Mi  
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service 
metadata:
  name: java
  labels:
    app: web
spec:
  selector:
    app: web
    version: blue
  type: NodePort
  ports:
  - nodePort: 31114
    port: 8010
    targetPort: 8010
